spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false


  datasource:
    url: jdbc:h2:file:./db
    username: sa
    password: sa

  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db\changelog\changes\changelog-master.xml
    enabled: true
    drop-first: false